language: go

install:
  - go get -d -t -v ./... && go build -v ./...

go:
  - 1.5
  - 1.6
  - 1.7
  - tip

script:
  - go vet ./...
  - go test -v ./cmd/... ./filter/... ./input/... ./output/...
  - go build
  - go install
  - test -n "$TRAVIS_TAG" || go run main.go --skip-validate --skip-publish

after_success:
  - go clean
  - test -n "$TRAVIS_TAG" && go run main.go
