language: go

install:
  - go get -d -t -v ./... && go build -v ./...

go:
  - 1.7
  - 1.8
  - tip

script:
  - go vet ./...
  - go test -v ./cmd/... ./filter/... ./input/... ./output/...
  - go build
  - go install

after_success:
  - go clean
